added centralized log function added DEBUG_MODE moved to crond in service instead of janky loop

diff --git a/scripts/config b/scripts/config
--- a/scripts/config
+++ b/scripts/config
@@ -1,9 +1,25 @@
 #!/bin/bash
 . "variables"
 
+log () {
+  if [[ -z "${1}" ]]; then
+    log "ERROR" "log level required"
+    exit 3
+  fi
+
+  if [[ -z "${2}" ]]; then
+    log "ERROR" "log message required"
+    exit 3
+  fi
+
+  if [[ "$(printenv DEBUG_ENABLED)" == "1" ]] || [[ ${1} != "DEBUG" ]]; then
+    echo "$(date "$(printenv DATE_FORMAT)") ${1}: ${2}"
+  fi
+}
+
 rclone_unmount () {
   if [[ -z "${1}" ]]; then
-    echo "$(date "$(printenv DATE_FORMAT)") Error: unmount path required"
+    log "ERROR" "unmount path required"
     exit 3
   fi
 
@@ -11,7 +27,7 @@ rclone_unmount () {
 
   while [[ "$(ls -A ${1})" ]]
   do
-    echo "$(date "$(printenv DATE_FORMAT)") NOTICE: Waiting for unmount of ${1} ..."
+    log "WARN" "Waiting for unmount of ${1} ..."
     sleep 1
   done
 }
@@ -19,20 +35,20 @@ rclone_unmount () {
 check_running () {
   parent=$(ps $PPID | tail -n 1 | awk "{print \$6}")
   if [[ ${parent} != "/usr/local/bin/runscript" ]]; then
-    echo "$(date "$(printenv DATE_FORMAT)") ERROR: Cannot run $(basename "$0") directly. Called from ${parent}. Aborting."
+    log "ERROR" "Cannot run $(basename "$0") directly. Called from ${parent}. Aborting."
     exit 3
   fi
 }
 check_rclone_read () {
 	if [[ ! "${rclone_read_endpoint}" == *: ]]; then
-		echo "$(date "$(printenv DATE_FORMAT)") ERROR: Missing colon (:) in RCLONE_READ_ENDPOINT (${rclone_read_endpoint})"
+		log "ERROR" "Missing colon (:) in RCLONE_READ_ENDPOINT (${rclone_read_endpoint})"
     sleep 5000
 		exit 02
 	fi
 
 	if [[ "$(rclone listremotes ${rclone_config} | grep "${rclone_read_endpoint}" | wc -l)" == "0" ]]; then
-		echo "$(date "$(printenv DATE_FORMAT)") ERROR: RCLONE_READ_ENDPOINT (${rclone_read_endpoint}) endpoint has not been created within rclone"
-		echo "$(date "$(printenv DATE_FORMAT)") ERROR: Run 'docker exec -ti <DOCKER_CONTAINER> rclone_setup'"
+		log "ERROR" "RCLONE_READ_ENDPOINT (${rclone_read_endpoint}) endpoint has not been created within rclone"
+		log "ERROR" "ERROR: Run 'docker exec -ti <DOCKER_CONTAINER> rclone_setup'"
     sleep 5000
 		exit 02
 	fi
@@ -40,15 +56,15 @@ check_rclone_read () {
 
 check_rclone_cloud () {
 	if [[ ! "${rclone_cloud_endpoint}" == *: ]]; then
-		echo "$(date "$(printenv DATE_FORMAT)") ERROR: Missing colon (:) in RCLONE_CLOUD_ENDPOINT (${rclone_cloud_endpoint})"
+		log "ERROR" "Missing colon (:) in RCLONE_CLOUD_ENDPOINT (${rclone_cloud_endpoint})"
 		printf "\n\n"
     sleep 5000
 		exit 02
 	fi
 
 	if [[ "$(rclone listremotes ${rclone_config} | grep "${rclone_cloud_endpoint}" | wc -l)" == "0" ]]; then
-		echo "$(date "$(printenv DATE_FORMAT)") ERROR: RCLONE_CLOUD_ENDPOINT (${rclone_cloud_endpoint}) endpoint has not been created within rclone"
-		echo "$(date "$(printenv DATE_FORMAT)") ERROR: Run 'docker exec -ti <DOCKER_CONTAINER> rclone_setup'"
+		log "ERROR" "RCLONE_CLOUD_ENDPOINT (${rclone_cloud_endpoint}) endpoint has not been created within rclone"
+		log "ERROR" "Run 'docker exec -ti <DOCKER_CONTAINER> rclone_setup'"
     sleep 5000
 		exit 02
 	fi
